package com.telus.csm.ewlnsvs.soap.webservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.apache.log4j.Logger;

import com.telus.csm.ewlnsc.soap.webservice.SalesServiceSoapBase;
import com.telus.csm.ewlnsvs.ws.EnterpriseSalesValidationServicePortType;
import com.telus.csm.ewlnsvs.ws.ServiceException;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetCustomerEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetCustomerEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetFutureDatedSalesEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetFutureDatedSalesEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetNumberPortInEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetNumberPortInEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSalesEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSalesEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetServiceEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetServiceEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSubscriberEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSubscriberEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidatePendingTransactionForResumeResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidatePendingTransactionForResumeType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderItemResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderItemType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderResponse;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.Ping;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse;
/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated
 * source version: 2.1
 *
 */
@WebService(portName = "EnterpriseSalesValidationServicePort", serviceName = "EnterpriseSalesValidationService_v5_0", targetNamespace = "http://telus.com/wsdl/MSO/ChannelSalesMgmt/EnterpriseSalesValidationService_5", wsdlLocation = "/wsdls/EnterpriseSalesValidationService_v5_0.wsdl", endpointInterface = "com.telus.csm.ewlnsvs.ws.EnterpriseSalesValidationServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class EnterpriseSalesValidationService extends SalesServiceSoapBase implements
	EnterpriseSalesValidationServicePortType {

	Logger logger = Logger.getLogger(EnterpriseSalesValidationService.class);
	
	@Override
	protected Object getNewServiceImpl() {
		return new EnterpriseSalesValidationServiceImpl();
	}

	private EnterpriseSalesValidationServicePortType getProxy() {
		return (EnterpriseSalesValidationServicePortType) getServiceProxy();
	}


	@Override
	public GetSalesEligibilityResponseType getSalesEligibility(GetSalesEligibilityType parameters)
			throws ServiceException {
		return getProxy().getSalesEligibility(parameters);
	}

	@Override
	public GetSubscriberEligibilityResponseType getSubscriberEligibility(GetSubscriberEligibilityType parameters)
			throws ServiceException {
		return getProxy().getSubscriberEligibility(parameters);
	}

	@Override
	public ValidateSalesOrderResponse validateSalesOrder(ValidateSalesOrder parameters) throws ServiceException {
		return getProxy().validateSalesOrder(parameters);
	}

	@Override
	public GetNumberPortInEligibilityResponseType getNumberPortInEligibility(GetNumberPortInEligibilityType parameters)
			throws ServiceException {
		return getProxy().getNumberPortInEligibility(parameters);
	}

	@Override
	public GetFutureDatedSalesEligibilityResponseType getFutureDatedSalesEligibility(
			GetFutureDatedSalesEligibilityType parameters) throws ServiceException {
		return getProxy().getFutureDatedSalesEligibility(parameters);
	}

	@Override
	public ValidatePendingTransactionForResumeResponseType validatePendingTransactionForResume(
			ValidatePendingTransactionForResumeType parameters) throws ServiceException {
		return getProxy().validatePendingTransactionForResume(parameters);
	}

	@Override
	public ValidateSalesOrderItemResponseType validateSalesOrderItem(ValidateSalesOrderItemType parameters)
			throws ServiceException {
		return getProxy().validateSalesOrderItem(parameters);
	}

	@Override
	public GetCustomerEligibilityResponseType getCustomerEligibility(GetCustomerEligibilityType parameters)
			throws ServiceException {
		return getProxy().getCustomerEligibility(parameters);
	}

	@Override
	public PingResponse ping(Ping parameters) throws ServiceException {
		return getProxy().ping(parameters);
	}

	@Override
	public GetServiceEligibilityResponseType getServiceEligibility(GetServiceEligibilityType parameters)
			throws ServiceException {
		// TODO Auto-generated method stub
		return null;
	}
	
}
