openapi: 3.0.0
info:
  title: CommerceProductQualificationBridge API
  description: This is a CommerceProductQualificationBridge API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/m_and_m/CommerceProductQualificationBridge/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: CommerceProductQualificationBridge
  description: Calls to CommerceProductQualificationBridge
paths:
  /application/{applicationId}/product-qualification:
    get:
      tags:
      - CommerceProductQualificationBridge
      summary: getAvailableProducts
      description: |
        By passing in the appropriate options, you can search for
        available products in the system
      operationId: getAvailableProducts
      parameters:
      - name: transactionId
        in: header
        description: business transaction id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: applicationId
        in: path
        description: applicationId
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: customerId
        in: query
        description: customerId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: accountId
        in: query
        description: accountId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: addressId
        in: query
        description: addressId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: provinceCd
        in: query
        description: provinceCd
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: city
        in: query
        description: city
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: qualByServiceId
        in: query
        description: qualByServiceId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: correlationId
        in: query
        description: correlationId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: salesRepId
        in: query
        description: salesRepId
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: channelOutletId
        in: query
        description: channelOutletId
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductQualification'
        400:
          description: |
            *Bad Request* - The server cannot process the request due to a malformed
            syntax. The response can be caused by missing mandatory query
            parameters, invalid value in the query parameters, validation
            exceptions, and so on.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: |
            *Not Found* - The server did not find anything matching the request URI.
            The response can be caused by missing path parameters, invalid WEB
            resource, and so on.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: |
            *Internal Server Error* - The server encountered an unexpected condition
            that prevented it from fulfilling the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ProductQualification:
      type: object
      properties:
        serviceAddress:
          $ref: '#/components/schemas/ServiceAddress'
        serviceId:
          type: string
        productList:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        gponEttsInd:
          type: boolean
        mduIndicator:
          type: boolean
        forborneIndicator:
          type: boolean
        changeOfTechnologyInd:
          type: string
    Product:
      type: object
      properties:
        productLine:
          type: string
        productTypeCd:
          type: string
        callingFeature:
          type: string
        maxTvProfile:
          type: string
        productTierCd:
          type: string
        productRanking:
          type: integer
        unavailableInd:
          type: boolean
        unavailableReasonCd:
          type: string
        unqualifiedReasonCd:
          type: string
    ServiceAddress:
      type: object
      properties:
        addressId:
          type: string
        streetNum:
          type: string
        streetName:
          type: string
        unitType:
          type: string
        vector:
          type: string
        unit:
          type: string
        city:
          type: string
        provinceCd:
          type: string
        countryCd:
          type: string
        postalCd:
          type: string
        ruralRouteNumber:
          type: string
    Error:
      required:
      - code
      - reason
      type: object
      properties:
        code:
          type: string
          description: |
            Application relevant detail, defined in the API or a common list
        reason:
          type: string
          description: |
            Explanation of the reason for the error which can be shown to a client user
        message:
          type: array
          description: |
            More details and corrective actions related to the error which can be shown to a client user
          items:
            $ref: '#/components/schemas/Message'
        status:
          type: string
          description: |
            HTTP Error code extension
        traceId:
          type: string
          description: |
            The unique tracker ID used to facilitate troubleshooting
        characteristic:
          type: array
          description: |
            The relevant parameter that is associated with this error
          items:
            $ref: '#/components/schemas/ErrorCharacteristic'
      description: |
        "Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)""
    Message:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
        text:
          type: string
    ErrorCharacteristic:
      type: object
      properties:
        name:
          type: string
          description: |
            The non localized name identifier of the characteristic
        value:
          type: string
          description: |
            The value of the characteristic
      description: |
        A parameter that is associated with this entity
