
package com.telus.csm.ewlnsvs.ws;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetCustomerEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetCustomerEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetFutureDatedSalesEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetFutureDatedSalesEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetNumberPortInEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetNumberPortInEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSalesEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSalesEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetServiceEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetServiceEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSubscriberEligibilityResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSubscriberEligibilityType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidatePendingTransactionForResumeResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidatePendingTransactionForResumeType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderItemResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderItemType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderResponse;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.Ping;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "EnterpriseSalesValidationServicePort", serviceName = "EnterpriseSalesValidationService_v5_0", targetNamespace = "http://telus.com/wsdl/MSO/ChannelSalesMgmt/EnterpriseSalesValidationService_5", wsdlLocation = "/wsdls/EnterpriseSalesValidationService_v5_0.wsdl", endpointInterface = "com.telus.csm.ewlnsvs.ws.EnterpriseSalesValidationServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class EnterpriseSalesValidationService_v5_0_EnterpriseSalesValidationServicePortImpl
    implements EnterpriseSalesValidationServicePortType
{


    public EnterpriseSalesValidationService_v5_0_EnterpriseSalesValidationServicePortImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSalesEligibilityResponseType
     * @throws ServiceException
     */
    public GetSalesEligibilityResponseType getSalesEligibility(GetSalesEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetSubscriberEligibilityResponseType
     * @throws ServiceException
     */
    public GetSubscriberEligibilityResponseType getSubscriberEligibility(GetSubscriberEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderResponse
     * @throws ServiceException
     */
    public ValidateSalesOrderResponse validateSalesOrder(ValidateSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetNumberPortInEligibilityResponseType
     * @throws ServiceException
     */
    public GetNumberPortInEligibilityResponseType getNumberPortInEligibility(GetNumberPortInEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetFutureDatedSalesEligibilityResponseType
     * @throws ServiceException
     */
    public GetFutureDatedSalesEligibilityResponseType getFutureDatedSalesEligibility(GetFutureDatedSalesEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidatePendingTransactionForResumeResponseType
     * @throws ServiceException
     */
    public ValidatePendingTransactionForResumeResponseType validatePendingTransactionForResume(ValidatePendingTransactionForResumeType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.ValidateSalesOrderItemResponseType
     * @throws ServiceException
     */
    public ValidateSalesOrderItemResponseType validateSalesOrderItem(ValidateSalesOrderItemType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetCustomerEligibilityResponseType
     * @throws ServiceException
     */
    public GetCustomerEligibilityResponseType getCustomerEligibility(GetCustomerEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesvalidationservicerequestresponse_v5.GetServiceEligibilityResponseType
     * @throws ServiceException
     */
    public GetServiceEligibilityResponseType getServiceEligibility(GetServiceEligibilityType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse
     * @throws ServiceException
     */
    public PingResponse ping(Ping parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

}
