
package com.telus.csm.ewlnsms.ws;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CancelSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CancelSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteSalesBatchOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteWirelessSalesBatchOrderResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesBatchOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrderItem;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrderItemResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateWirelessSalesBatchOrderResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateWirelineSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateWirelineSalesOrderResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.GetSalesOrderByShoppingCartResponseType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.GetSalesOrderByShoppingCartType;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReserveSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReserveSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReturnSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReturnSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.SubmitSalesToPos;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.SubmitSalesToPosResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UnreserveSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UnreserveSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdatePendingSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdatePendingSalesOrderResponse;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdateSalesOrder;
import com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdateSalesOrderResponse;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.Ping;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "EnterpriseSalesFulfillmentServicePort", serviceName = "EnterpriseSalesFulfillmentService_v5_0", targetNamespace = "http://telus.com/wsdl/MSO/ChannelSalesMgmt/EnterpriseSalesFulfillmentService_5", wsdlLocation = "/wsdls/EnterpriseSalesFulfillmentService_v5_0.wsdl", endpointInterface = "com.telus.csm.ewlnsms.ws.EnterpriseSalesFulfillmentServicePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class EnterpriseSalesFulfillmentService_v5_0_EnterpriseSalesFulfillmentServicePortImpl
    implements EnterpriseSalesFulfillmentServicePortType
{


    public EnterpriseSalesFulfillmentService_v5_0_EnterpriseSalesFulfillmentServicePortImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrderResponse
     * @throws ServiceException
     */
    public CreateSalesOrderResponse createSalesOrder(CreateSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateWirelessSalesBatchOrderResponseType
     * @throws ServiceException
     */
    public CreateWirelessSalesBatchOrderResponseType createSalesBatchOrder(CreateSalesBatchOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteSalesOrderResponse
     * @throws ServiceException
     */
    public CompleteSalesOrderResponse completeSalesOrder(CompleteSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CompleteWirelessSalesBatchOrderResponseType
     * @throws ServiceException
     */
    public CompleteWirelessSalesBatchOrderResponseType completeSalesBatchOrder(CompleteSalesBatchOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReserveSalesOrderResponse
     * @throws ServiceException
     */
    public ReserveSalesOrderResponse reserveSalesOrder(ReserveSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UnreserveSalesOrderResponse
     * @throws ServiceException
     */
    public UnreserveSalesOrderResponse unreserveSalesOrder(UnreserveSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.SubmitSalesToPosResponse
     * @throws ServiceException
     */
    public SubmitSalesToPosResponse submitSalesToPos(SubmitSalesToPos parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CancelSalesOrderResponse
     * @throws ServiceException
     */
    public CancelSalesOrderResponse cancelSalesOrder(CancelSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdatePendingSalesOrderResponse
     * @throws ServiceException
     */
    public UpdatePendingSalesOrderResponse updatePendingSalesOrder(UpdatePendingSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.UpdateSalesOrderResponse
     * @throws ServiceException
     */
    public UpdateSalesOrderResponse updateSalesOrder(UpdateSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.ReturnSalesOrderResponse
     * @throws ServiceException
     */
    public ReturnSalesOrderResponse returnSalesOrder(ReturnSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateSalesOrderItemResponse
     * @throws ServiceException
     */
    public CreateSalesOrderItemResponse createSalesOrderItem(CreateSalesOrderItem parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.CreateWirelineSalesOrderResponseType
     * @throws ServiceException
     */
    public CreateWirelineSalesOrderResponseType createWirelineSalesOrder(CreateWirelineSalesOrder parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.srv.mso.channelsalesmgmt.enterprisesalesfulfillmentservicerequestresponse_v5.GetSalesOrderByShoppingCartResponseType
     * @throws ServiceException
     */
    public GetSalesOrderByShoppingCartResponseType getSalesOrderByShoppingCart(GetSalesOrderByShoppingCartType parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v1.PingResponse
     * @throws ServiceException
     */
    public PingResponse ping(Ping parameters)
        throws ServiceException
    {
        //replace with your impl here
        return null;
    }

}
