package com.telus.csm.ewlnsc.domain;

public enum ShoppingCartValidationErrorCodes {
	// OMS9 shopping cart validation
	DUPLICATE_INTERNET_PRODUCT_IN_CART("ESS_SC_VALIDATION_00001"),
	DUPLICATE_TV_PRODUCT_IN_CART("ESS_SC_VALIDATION_00002"),
	DUPLICATE_SINGLE_LINE_PRODUCT_IN_CART("ESS_SC_VALIDATION_00003"),
	
	SERVICE_ADDRESS_NOT_PROVIDED("ESS_SC_VALIDATION_00004"),
	
	CUSTOMER_NOT_FOUND("ESS_SC_VALIDATION_00005"),
	
	PAY_CHANNEL_ID_NOT_FOUND("ESS_SC_VALIDATION_00006"),
	
	SERVICE_ADDRESS_NOT_FOUND("ESS_SC_VALIDATION_00007"),
	
	NON_STACKABLE_MARKET_OFFER_DISCOUNT("ESS_SC_VALIDATION_00008"),
	MARKET_DISCOUNT_CODES_NOT_EXISTING("ESS_SC_VALIDATION_00009"),
	
	SWEETENER_OFFER_NOT_FOUND("ESS_SC_VALIDATION_00010"),
	SWEETENER_DISCOUNT_CODES_NOT_FOUND("ESS_SC_VALIDATION_00011"),
	NON_STACKABLE_SWEETENER_DISCOUNT("ESS_SC_VALIDATION_00012"),
	
	INTERNET_PROD_NOT_QUALIFY("ESS_SC_VALIDATION_00013"),
	INTERNET_PROD_CODE_NOT_FOUND("ESS_SC_VALIDATION_00013"),
	
	INTERNET_BEST_FEASIBILITY("ESS_SC_VALIDATION_00014"),
	
	FEASIBILITY_RESP_NULL("ESS_SC_VALIDATION_00015"),
	
	INTERNET_PROD_QUALIFICATION_RESP_NULL("ESS_SC_VALIDATION_00016"),
	
	SHIPPED_EQUIPMENT_MISSING_SHIPPING_ADDRESS("ESS_SC_VALIDATION_00017"),

	MISSING_INPUT_VALIDATION("ESS_SC_VALIDATION_00018"),
	
	UNSUPPORTED_ELEMENTS_VALIDATION("ESS_SC_VALIDATION_00019"),
	
	EQUIPMENT_WITHIN_MARKET_OFFER("ESS_SC_VALIDATION_00020"),
	
	MARKET_OFFER_VALIDATION("ESS_SC_VALIDATION_00022"),
	
	CONSOLIDATED_ACCOUNT_VALIDATION("ESS_SC_VALIDATION_00023"),
	
	SERVICE_ADDRESS_VALIDATION("ESS_SC_VALIDATION_00024"),
	
	EQUIPMENT_NOT_FOUND_IN_MARKET_OFFER("ESS_SC_VALIDATION_00025"),
	
	WINBACK_WITHOUT_DISCONNECT_ORDER("ESS_SC_VALIDATION_00026"),
	
	DISCOUNT_CROSS_PRODUCT_DEPENDENCY("ESS_SC_VALIDATION_00027"),
	
	O_OA_CONFIG("ESS_OP_VALIDATION_10000"),

	PRICING("ESS_OP_VALIDATION_10001"),
	
	ACCESSORY_OFFER_INELIBILE("ESS_SC_VALIDATION_00028"), 
	ACCESSORY_OFFER_INCOMPATIBLE_DISCOUNTS("ESS_SC_VALIDATION_00029"),
	
	//ProductItem validation rules
	PRODUCT_ITEM_CANNOT_CARRY_OVER("ESS_SC_VALIDATION_00030"),
	
	AVAILABLE_PRODUCT_ITEM_DELEGATE_NULL("ESS_SC_VALIDATION_00031"),
	
	PRODUCT_ITEM_MISSING_PARENT_FROM_MARKET_OFFER("ESS_SC_VALIDATION_00032"),
	
	CHILD_OF_REMOVED_PRODUCT_ITEM("ESS_SC_VALIDATION_00033"),

	NO_PORTS_AVAILABLE("ESS_SC_VALIDATION_00034"),
	
	INTERNET_EQUIPMENT_FEASIBLE("ESS_SC_VALIDATION_00035"),
	
	MARKET_OFFER_WINBACK_DISCOUNT("ESS_SC_VALIDATION_00036"),
	
	//Misc Rule (02***)
	PORT_IN_DATE_PROVIDE_DATE_NOT_MATCHED("ESS_SC_VALIDATION_02001"),
	
	//Product Component Rule (05***)
	MARKET_OFFER_PRODUCT_COMPONENT_NOT_MATCHED("ESS_SC_VALIDATION_05001"),
	
	//Discount Rule (06***)
	MANDATORY_INCLUDED_DISCOUNT_NON_IN_CART("ESS_SC_VALIDATION_06001"),
	RECONTRACTING_DISCOUNT_PRODUCT_NOT_RECONTRACTING("ESS_SC_VALIDATION_06002"),
	PROMOTIONS_CART("ESS_SC_VALIDATION_06003"),
	
	//Features Rule (07***)
	CALL_REVEAL_WITHOUT_CALL_DISPLAY("ESS_SC_VALIDATION_07001"),
	MANDATORY_FEATURE_NOT_IN_CART("ESS_SC_VALIDATION_07002"),
	FEATURE_NOT_IN_OFFER("ESS_SC_VALIDATION_07003"),
	SMART_RING_LISTING_WITHOUT_FEATURE("ESS_SC_VALIDATION_07004"),
	SMART_RING_FEATURE_WITHOUT_LISTING("ESS_SC_VALIDATION_07005"),
	
	//AddOn Rule (08***)
	MANDATORY_ADDON_NOT_IN_CART("ESS_SC_VALIDATION_08001"),
	DISCOUNT_MISSING_ADDON("ESS_SC_VALIDATION_08002"),
	

	//Booking rules (09***) 
	BOOKING_DATE_NOT_PROVIDED("ESS_SC_VALIDATION_09001")
	;
	

	private final String code;

	private ShoppingCartValidationErrorCodes(String code) {
		this.code = code;
	}
	public String getCode() {
		return code;
	}

}
